config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: %i[new create destroy]

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout

  resources :links

  root 'links#new'

  get '/:short_url', to: 'links#redirect', as: :l
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
require 'uri'

class Link < ApplicationRecord
  before_save :shortened_url

  validates :original_url, presence: true
  validates_format_of :original_url, with: URI::DEFAULT_PARSER.make_regexp, message: 'must be URL'

  private

  def shortened_url
    self.short_url = 6.times.map { [*'0'..'9', *'a'..'z'].sample }.join until Link.find_by_short_url(short_url).nil?
  end

end

app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(auth_hash)
    user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
    user.uid = auth_hash['uid']
    user.provider = auth_hash['provider']
    user.name = auth_hash['info']['name']
    user.save!
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_current_user

  def set_current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def check_logged_in
    if @current_user.blank?
      redirect_to root_path, notice: 'Not logged in user'
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :check_logged_in, only: :index

  def index
    @links = Link.all.paginate(page: params[:page], per_page: 10)
  end

  def show
    @link = Link.find(params[:id])
  end

  def redirect
    @link = Link.where(short_url: params[:short_url]).first
    @link.increment!(:clicks)

    redirect_to @link.original_url
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)

    if @link.save
      redirect_to link_url(@link)
    else
      render 'new'
    end
  end

  private

  def link_params
    params.require(:link).permit(:original_url, :clicks)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include ApplicationHelper

  def new
  end

  def create
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Welcome! You have been logged in'
    else
      redirect_to login_path, alert: 'Sorry, there was an error'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'You have been logged out successfully'
  end

  def auth_failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Url Shortener</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%=render 'layouts/partials/header' %>
  	<%=render 'layouts/partials/flash_messages' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/partials/_flash_messages.html.erb
<div class="wrapper">
  <% if flash.any? %>
    <div id="notification">
      <% flash.each do |key, msg| %>
        <%= content_tag :div, msg, class: [key.to_s], id: "notification" %>
      <% end %>
      <a id="close">[close]</a>
    </div>
  <% end %>
</div>

app/views/layouts/partials/_form_error_messages.html.erb
<% if object.errors.any? %>
  <ul class="errors">
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/partials/_header.html.erb
<nav class="navbar navbar-fixed-top">
  <div class="container-fluid">
		<div class="navbar-header">
			<% if @current_user %>
			  <p class="navbar-text">Signed in as <%=@current_user.name %></p>
			  <a class="btn btn-success navbar-btn" href='/links'>Explore Links</a>
			  <a class="btn btn-default navbar-btn" href='/logout'>Logout</a>
			<% else %>
			  <h2>Join us and get access to Links Dashboard!</h2>
			  <a class="btn btn-default navbar-btn" href='/auth/facebook'>Sign in with Facebook</a>
			  <a class="btn btn-default navbar-btn" href='/auth/twitter'>Sign in with Twitter</a>
			<% end %>
		</div>
  </div>
</nav>

app/views/links/index.html.erb
<div class="container">
  <p class="move-back">&larr; <%=link_to 'Home Page', root_path %></p>
  <% if @links.present? %>
    <table class="styled">
      <thead>
        <tr>
          <th>Original Link</th>
          <th>Shortened Link <br />(domain.name/)</th>
          <th>Clicks count</th>
        </tr>
      </thead>
      <tbody>
      <% @links.each do |link| %>
        <tr>
          <td><%=link_to link.original_url, link_path(link) %></td>
          <td><%=link.short_url %></td>
          <td><%=link_to link.clicks %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    <p class="nothing">There are no any links yet</p>
  <% end %>
  <%=will_paginate @links, :renderer => BootstrapPagination::Rails %></div>
</div>

app/views/links/new.html.erb
<div class="container">
  <div class="wrapper">
  	<h3>Paste an URL:</h3>
  	<div class="url-form">
		  <%= render partial: 'layouts/partials/form_error_messages', locals: { object: @link } %>
		  <%=form_for @link, url: links_path do |f| %>
		    <div><%=f.text_field :original_url %></div>
		    <div><%=f.submit 'Make it shorter!' %></div>
		  <% end %>
		</div>
  </div>
</div>

app/views/links/show.html.erb
<div class="container">
	<p class="move-back">&larr; <%=link_to 'Home Page', root_path %></p>
  <div class="wrapper">
  	<h3>Your Pretty Shortened URL:</h3>
  	<div class="url-form">
	  	<%=form_for @link, url: links_path do |f| %>
	      <div class="short"><%= l_url(@link.short_url) %></div>
	    <% end %>
    </div>
	</div>
</div>